import sys
from PyInstaller.utils.hooks import collect_data_files, collect_submodules

block_cipher = None

hidden_imports = collect_submodules('uvicorn') + collect_submodules('aiosqlite') + [
    'uvicorn.logging',
    'uvicorn.loops',
    'uvicorn.loops.auto',
    'uvicorn.protocols',
    'uvicorn.protocols.http',
    'uvicorn.protocols.http.auto',
    'uvicorn.protocols.websockets',
    'uvicorn.protocols.websockets.auto',
    'uvicorn.lifespan',
    'uvicorn.lifespan.on',
    'aiosqlite',
    'desktop',
    'desktop.main',
    'desktop.server',
    'desktop.tray',
    'desktop.updater',
    'pystray',
    'pystray._win32',
    'webview',
    'webview.platforms',
    'webview.platforms.winforms',
    'filelock',
    # App modules dynamically imported
    'app',
    'app.main',
    'app.config',
    'app.database',
    'app.models',
    'app.models.api_provider',
    'app.models.base',
    'app.models.billing',
    'app.models.message',
    'app.models.plan_template',
    'app.models.reference',
    'app.models.rule',
    'app.models.session',
    'app.models.app_setting',
    'app.models.skill',
    'app.routers',
    'app.routers.session',
    'app.routers.api_provider',
    'app.routers.billing',
    'app.routers.dashboard',
    'app.routers.download',
    'app.routers.plan_template',
    'app.routers.prompt',
    'app.routers.reference',
    'app.routers.rule',
    'app.routers.settings',
    'app.routers.skill',
    'app.services',
    'app.services.generate_service',
    'app.services.agent_service',
    'app.services.agent_intent_service',
    'app.services.agent_bridge',
    'app.services.api_manager',
    'app.services.billing_service',
    'app.services.plan_executor',
    'app.services.plan_template_service',
    'app.services.prompt_optimizer',
    'app.services.reference_manager',
    'app.services.rule_engine',
    'app.services.session_manager',
    'app.services.settings_service',
    'app.services.skill_engine',
    'app.services.task_manager',
    'app.schemas',
    'app.schemas.api_provider',
    'app.schemas.billing',
    'app.schemas.plan_template',
    'app.schemas.session',
    'app.tools',
    'app.tools.base',
    'app.tools.generate_image',
    'app.tools.image_search',
    'app.tools.plan',
    'app.tools.web_search',
    'app.utils',
    'app.utils.crypto',
    'app.utils.image_client',
    'app.utils.llm_client',
    'app.core',
    'app.core.events',
    'app.middleware',
]

datas = [
    ('frontend/dist', 'frontend/dist'),
    ('desktop/assets', 'desktop/assets'),
]

excludes = [
    'tkinter',
    'test',
    'unittest',
    'pytest',
    'setuptools',
    'pip',
    'wheel',
]

a = Analysis(
    ['desktop/main.py'],
    pathex=['backend'],
    binaries=[],
    datas=datas,
    hiddenimports=hidden_imports,
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=excludes,
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='LamImager',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=False,
    icon='desktop/assets/lamimager.ico',
)

coll = COLLECT(
    exe,
    a.binaries,
    a.zipfiles,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name='LamImager',
)
